excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Azrael-the-Atheist.github.io
title: Azrael the Atheist
tagline: Religion is a mental illness!
description: Azrael, destroyer of delusions
paginate: 5